# Essentials


In this part of the script I am going to go through some 

## Numeric types


First, let's focus on different and most basic (and useful for daily use) numerical types of objects in `Julia`.


| Type|Desc. |Smallest number|Largest number|
|-|-|-|-|
|`Int8` | signed integers   |$-2^7$| $2^7-1$|
|`UInt8`| unsigned integers (_read:_ natural numbers)| $0$ | $2^8$|
|`Int16` | signed integers   |$-2^{15}$| $2^{15}-1$|
|`UInt16`| unsigned integers (_read:_ natural numbers)| $0$ | $2^{16}$|
|`Int64` | signed integers   |$-2^{63}$| $2^{63}-1$|
|`UInt64`| unsigned integers (_read:_ natural numbers)| $0$ | $2^{64}$|

There is also an alias `Int` for integers with the default number of bits for your architecture (32 or 64).


In [27]:
x = 1

1

```{margin}

For quiet execution of line `x = 1`, we should add `;` at the end of the line. 
This way the assignment will be made without printing the result.

```

In [28]:
typeof(x)

Int64

We can explicitly force `Julia` to set the precision of our integers:

````{margin}
```{note}
In `Julia` we can use special unicode characters for naming objects, like `α`  or even `αₖʲ`. In VS Code, to get `α` you have to type `\alpha` and press `tab`. `αₖʲ` can be obtained by typing combination `\alpha`, `tab`, `\_k`, `tab`, `\^j`, `tab`.
```
````

In [86]:
α = Int8(2)


2

In [44]:
Int8(2^7-1)

127

However, we have to remember about the ranges of used types:

In [41]:
Int8(2^8) #Error message

LoadError: InexactError: trunc(Int8, 256)

Unsigned integers are not super useful due to their default hexadecimal notation: 

In [147]:
@show UInt(1018);

UInt(1018) = 0x00000000000003fa


Another type of numbers in `Julia` are floating-point values


|Type|Number of bits|
|--|--|
|`Float16`| 16|
|`Float32`| 32|
|`Float64`| 64|


Similarly to integers, `float` refers to floating-point values with the default number of bits for your architecture (32 or 64).

```{margin}
Notice the difference in letter capitalization: `float` vs. `Int`!
```

In [48]:
w = .2

0.2

In [49]:
typeof(w)

Float64

## Basic arithmetic operations

On the surface, arithmetic operations (`+`, `-`, `*`, `/`) in `Julia` are very similar to the ones known from such languages as `Matlab`:


In [64]:
x = 1
y = 2
x + y


3

For presenting results of the operation macro `@show` can be quite useful:

In [65]:
x = 1
y = 2
@show x + y + .2


x + y + 0.2 = 3.2


3.2

If we combine two different numeric types, `Julia` will try to coerce the less general object to more general one: 

In [75]:
x = Int(42)
y = float(.964)
@show z = x+y

typeof(z)

z = x + y = 42.964


Float64

You can use also `Lisp`-like syntax (which we find in `R` as well. Sometimes this can be very useful, and other times, it can be quite [scary](https://twitter.com/mjskay/status/1454952248937783304)):

In [78]:
+(x, y)

42.964

In [83]:
@show  ^(*( 3, +(1, 2) ), 5)

(3 * (1 + 2)) ^ 5 = 59049


59049

There are several ways to divide numbers. 
The most natural one is by using `/`:

In [93]:
@show 1/2 

1 / 2 = 0.5


0.5

If for some reason, we want to use common fractions instead of decimals, then we have to use `//` instead:

In [94]:
1//2

1//2

In [ ]:
Within common fractions, we can perform arithmetic operations:


In [107]:
@show 1//2+1//3;


1 // 2 + 1 // 3 = 5//6


In [113]:
@show (1//2)^10;

(1 // 2) ^ 10 = 1//1024


But due to coercion in operations over different types, we might lose it:

In [101]:
@show 1//2 + .25;
@show 1//2 + π;

1 // 2 + 0.25 = 0.75
1 // 2 + π = 3.641592653589793


We perform integer division by using `div` or `÷` (to get this symbol type `\div` and `tab`):

In [105]:
@show div(5,3);
@show   ÷(5,3);
@show     5÷3;

div(5, 3) = 1
5 ÷ 3 = 1
5 ÷ 3 = 1


We get remainder by using `rem` or `%`:

In [114]:
@show rem(5,3);
@show   %(5,3);
@show     5%3;

rem(5, 3) = 2
5 % 3 = 2
5 % 3 = 2


## Data structures




(arrays)=
### Arrays

Arrays are one of the most important data structures for economists. They are equivalent of vectors and matrices in `Matlab` or `R`. 
Arrays are multi-dimensional objects containing numbers (or different objects).


A vector is a one-dimensional array. To get a row vector you use the following convention:

In [115]:
A = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

You get column vectors by using `;` as the separator of elements:

In [116]:
B = [1; 2; 3]

3-element Vector{Int64}:
 1
 2
 3

All elements of arrays must be of the same type. In case of type incompatibility across elements, coercion is performed:

In [125]:
@show c = [1 π 2.3]

@show typeof(c) #It's Float64 despite the first element being an integer.

c = [1 π 2.3] = [1.0 3.141592653589793 2.3]
typeof(c) = Matrix{Float64}


Matrix{Float64} (alias for Array{Float64, 2})

In [126]:
X = [1 2 3;
     3 4 5]

2×3 Matrix{Int64}:
 1  2  3
 3  4  5

It is a good practice to initialize arrays before assigning values to their elements.
To create an empty one-dimensional array with `K` elements of type `TYPE` 
you use `Array{TYPE}(undef, K)`.
Below an illustrating example:

In [135]:
Array{Float64}(undef, 10)

10-element Vector{Float64}:
 2.2870031e-314
 2.305650118e-314
 2.287003298e-314
 2.287003377e-314
 2.2870034164e-314
 2.287003456e-314
 2.3056506396e-314
 2.287003535e-314
 2.2870032583e-314
 2.3376373433e-314

Argument `undef` means that nothing particular is assigned to all elements.
Instead, existing values stored previously in the memory are assigned.

To create an array of dimensions $K\times N\times S\times W$ you use
`Array{TYPE}(undef, K, N, S, W)`.
Below an illustrating example:


In [136]:
Array{Int}(undef, 2, 3, 2, 2)

2×3×2×2 Array{Int64, 4}:
[:, :, 1, 1] =
 1  4643474736  2
 1  4643474816  4

[:, :, 2, 1] =
 4643474896  5  4643475056
 4643474976  7  4643475136

[:, :, 1, 2] =
 8  4643475216  10
 9  4643475296  11

[:, :, 2, 2] =
 4643475376  12  4643475536
 4643475456  12  4643475616

To get an array with all elements constant, you use command `fill`:

In [156]:
A = fill(π^2, 4, 3)

4×3 Matrix{Float64}:
 9.8696  9.8696  9.8696
 9.8696  9.8696  9.8696
 9.8696  9.8696  9.8696
 9.8696  9.8696  9.8696

Arrays with zero elements can be constructed with `zeros`:

In [158]:
zeros(3,2)

3×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

To get an identity square matrix of dimension $K$ function `I` from package `LinearAlgebra` can be used:

````{margin}
To load package to the memory, you use `using PackageName`. To install packages you use `Pkg` package:
    ```
    using Pkg; Pkg.add("PackageName")
    ```
````

In [162]:
using LinearAlgebra
I(5)

5×5 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  1  ⋅  ⋅
 ⋅  ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  ⋅  1

```{margin}
`I` generates a matrix with boolean elements (with `true` and `false` values) but it can be used normally with arrays of other numeric types thanks to coercion.
```

Except square bracket notations, accessing arrays in `Julia` is almost one-to-one analogy to `Matlab`:

In [163]:
A = [1 2 3 4 5;
     6 7 5 9 12]

2×5 Matrix{Int64}:
 1  2  3  4   5
 6  7  5  9  12

In [174]:
size(A)

(2, 5)

In [165]:
A[1,:] #1st row

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [166]:
A[:,1] #1st column

2-element Vector{Int64}:
 1
 6

In [169]:
A[:,[1,3]] #1st and 3rd column

2×2 Matrix{Int64}:
 1  3
 6  5

In [172]:
A[:,3:end] #from 3rd to the last columns

2×3 Matrix{Int64}:
 3  4   5
 5  9  12

In [173]:
A[1,3:end] #1st row and from 3rd to the last columns

3-element Vector{Int64}:
 3
 4
 5

Just like with scalars, arithmetic operations on arrays of _the same dimensions_ work in an analogous way:

In [217]:
A = [1 2;3 4];
B = I(2);

In [218]:
A + B

2×2 Matrix{Int64}:
 2  2
 3  5

In [251]:
A*A

2×2 Matrix{Int64}:
  7  10
 15  22

In [260]:
A

2×2 Matrix{Int64}:
 1  2
 3  4

In [259]:
A' #transposition

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

In [258]:
A^(-1) #invert matrix

2×2 Matrix{Float64}:
 -2.0   1.0
  1.5  -0.5

In [257]:
A^(-1)*A #in fact, it works

2×2 Matrix{Float64}:
 1.0          0.0
 2.22045e-16  1.0

Nonetheless, if we try to add an object of different dimensions (including scalars),
we will get an error message, just like in an example below:

In [219]:
A + 1

LoadError: MethodError: no method matching +(::Matrix{Int64}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::Rational, ::Integer) at rational.jl:288
  ...

This can be perceived as a particularly bizzare and excessively formal thing. 
That said, at the development stage there were reasons for this.
Furthermore, notice that in Mathematics this type of operations, $\mathbb{A}+1$, in most cases is also forbidden.
One (extremely inefficient but didactically useful) solution to this problem is to increase the size of the smaller object by using `repeat`.
This function constructs an array by repeating the input _array_ a given number of times in each out of the provided dimension.

Thus, to compute $\mathbb{A}+1,$ we have to increase the size of $1$ in such a way that the new object fits the size of $\mathbb{A}$.
As we remember the size of $\mathbb{A}$ is $2\times 2.$
Just to double check, let's use function `size`.

In [399]:
size(A)

(2, 2)

```{margin}
The first argument of `repeat` is the input array (note that we need to write the array form `[1]` fort this reason that a scalar object `1` is not accepted by the function), next arguments are how many times in each dimension the object should be repeated.
```

In [ ]:
Below you can find `repeat` at play:

In [403]:
repeat([1], 3)

3-element Vector{Int64}:
 1
 1
 1

In [404]:
repeat([1], 3, 2)

3×2 Matrix{Int64}:
 1  1
 1  1
 1  1

In [405]:
repeat([1], 4, 3, 2)

4×3×2 Array{Int64, 3}:
[:, :, 1] =
 1  1  1
 1  1  1
 1  1  1
 1  1  1

[:, :, 2] =
 1  1  1
 1  1  1
 1  1  1
 1  1  1

In [410]:
repeat([1; 2], 2, 3) #input argument: column vector

4×3 Matrix{Int64}:
 1  1  1
 2  2  2
 1  1  1
 2  2  2

In [408]:
repeat([1 2], 2, 3) #input argument: row vector

2×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2

Consequently, we are in the position to compute $\mathbb{A}+1:$

In [411]:
A + repeat([1], 2, 2)

2×2 Matrix{Int64}:
 2  3
 4  5

An addition of two arrays of different sizes can be conducted analogously:

In [414]:
A + repeat([0; 1], 1, 2)

2×2 Matrix{Int64}:
 1  2
 4  5

:::{note}
That being said, by no means use this approach in your daily use.
A _much more recommended_ and **efficient** way to operate on objects of different sizes is to use broadcasting or mapping.
I discuss it in more details in [one of the further secions](broadcasting).
:::

#### Assignment operator (`=`) and arrays: easy for Pythonistas, confusing for Matlabians

What can be quite confusing at first for people with the `Matlab` background is how the assignment operator (`=`) works with arrays in `Julia`. 
In `Matlab` if we want to create a matrix `V1` that is a copy of another matrix `V0` it is enough to write:

```
    V1=V0
```

Henceforth, there are two _separate_ matrices in the memory, `V1` and `V0`. 
Any changes in either of those will not affect the other one.
In `Julia` this works in a very different way. 
Exactly like in `Python`, running `V1=V0` will create a new _pointer_ to the memory allocated for `V0`. 
Both objects, `V1` and `V0`, share the same information.
Consequently, any changes in the memory through accessing `V1` will affect the data pointed by `V0`, and vice versa.
Below you can find an illustration of this language feature.

In [199]:
@show V₀ = [1 2 3];

V₀ = [1 2 3] = [1 2 3]


In [201]:
@show V₁ = V₀;


V₁ = V₀ = [1 2 3]


Running `V₁ = V₀` will create a new pointer to the memory associated with `V₀`.
Now changes in either of those objects will affect both pointers:

In [203]:
@show V₁[1] = 420;
@show V₁;
@show V₀;

@show V₀[3] = 128;
@show V₁;
@show V₀;

V₁[1] = 420 = 420
V₁ = [420 2 128]
V₀ = [420 2 128]
V₀[3] = 128 = 128
V₁ = [420 2 128]
V₀ = [420 2 128]


```{margin}
_Note to myself:_ explain it using better words.
```

This feature of `Julia` can be especially confusing in iterative procedures with updating values, such as value function iterations. 
In this case, trying to create a copy of one array but making rather a new pointer instead will result in meeting the convergence criterion immediately after the first iteration (_terrible sentence_).
Obviously, this will not be correct.



A remedy to this issue can be simply addressed by using `deepcopy`, which creates a _new object in the memory_ that contains the same information as the copied object.

In [205]:
@show V₀ = [1 2 3];
@show V₁ = deepcopy(V₀);

V₀ = [1 2 3] = [1 2 3]
V₁ = deepcopy(V₀) = [1 2 3]


Now changes in either of those objects _will not_ affect values pointed by the other object:

In [206]:
@show V₁[1] = 420;
@show V₁;
@show V₀;

@show V₀[3] = 128;
@show V₁;
@show V₀;

V₁[1] = 420 = 420
V₁ = [420 2 3]
V₀ = [1 2 3]
V₀[3] = 128 = 128
V₁ = [420 2 3]
V₀ = [1 2 128]


An important thing that should be also stressed is that this feature works only in the presence of assignments without additional operations.
If, for instance, code `V₁ = 2*V₀` involves two operations: (1) multiplication `*(2,V₀)`; and (2) making pointer `V₁` to memory containing _results_ from computing `*(2,V₀)` in the past.
This means that memory spaces pointed by `V₁` and by `V₀` are two different things.

In [209]:
@show V₀ = [1 2 3];
@show V₁ = 2*V₀;

V₀ = [1 2 3] = [1 2 3]
V₁ = 2V₀ = [2 4 6]


In [208]:
@show V₁[1] = 420;
@show V₁;
@show V₀;

@show V₀[3] = 128;
@show V₁;
@show V₀;

V₁[1] = 420 = 420
V₁ = [420 4 6]
V₀ = [1 2 3]
V₀[3] = 128 = 128
V₁ = [420 4 6]
V₀ = [1 2 128]


### Dictionaries


Dictionaries are very useful objects that are particularly useful in my daily workflow. 
They are 



### Ranges



Ranges are quite intuitive objects.
They collect elements from a certain range of values.
They can be created either by using `:` operator (just like in `R` and `Matlab`) or by using `range` function.
For instance, if we want to create a range from 5 through 120, we can use two options:

In [282]:
@show 5:120;
@show range(5, stop=120);

5:120 = 5:120
range(5, stop = 120) = 5:120


Notice that you are not allowed to use `range(5,120)` because at least one of `length`, `stop`, or `step` must be specified explicitely.


If we want, we can set the size step. Again, it can be done in two ways:

In [281]:
@show 5:.5:120;
@show range(5, stop=120, step=.5);

5:0.5:120 = 5.0:0.5:120.0
range(5, stop = 120, step = 0.5) = 5.0:0.5:120.0


You can perform normal arithmetic operations:

In [289]:
(1:5)*2

2:2:10

However, be careful about the order of operations. 
Arithmetic operations have a higher priority in `Julia`.
For `Matlab` users that is the same, but it might be problematic for `R` users, where the order is different.
In `Julia`if you type `1:5+1`, you will give you `1:6`, while in `R` you will get `2:6`.

In [290]:
1:5+1

1:6

Another important difference between other languages and `Julia` is the fact that arrays and ranges are not compatible with each other.
This means that arithmetic operations will give you an error message, even if objects are of the same size: 

In [293]:
1:3 + [1; 2; 3]

LoadError: MethodError: no method matching +(::Int64, ::Vector{Int64})
For element-wise addition, use broadcasting with dot syntax: scalar .+ array
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::Union{Int16, Int32, Int64, Int8}, ::BigInt) at gmp.jl:534
  ...

You can extract all element from a range and create an array by using `collect`:

In [297]:
collect(1:3)

3-element Vector{Int64}:
 1
 2
 3

In this case, arithmetic operations are allowed:


In [298]:
collect(1:3) + [1; 2; 3]

3-element Vector{Int64}:
 2
 4
 6

In [311]:
using FIGlet

In [317]:
function random_economist()
    using sample
enddddd

 _____ _              _     _                  _   _ _
/  ___| |            (_)   | |                | | | | |
\ `--.| |_ __ _ _ __  _ ___| | __ ___      __ | | | | | __ _ _ __ ___
 `--. \ __/ _` | '_ \| / __| |/ _` \ \ /\ / / | | | | |/ _` | '_ ` _ \
/\__/ / || (_| | | | | \__ \ | (_| |\ V  V /  | |_| | | (_| | | | | | |
\____/ \__\__,_|_| |_|_|___/_|\__,_| \_/\_/    \___/|_|\__,_|_| |_| |_|





In [310]:
Σ([1 2 3])

6

### Tuples

To be written. An example of a tuple:

In [301]:
(1,2,3)

(1, 2, 3)

(broadcasting)=
## Broadcasting (`.`): where arrays meet scalars


In [the section](arrays) describing arrays, we faced one seemingly bizzare obstacle in operating with objects of different data structures.
In our discussed example we tried to add a scalar number, $1,$ to a matrix $\mathbb{A}$ by running $\mathbb{A}+1.$
In `Julia` it is not possible. 
While trying running `A+1` you get an error message.
We addressed this problem by using function `repeat`.
Here I present a much more recommended approach and to this end I will use function `broadcast`.


To perform this type of procedures, you have to broadcast an addition operator `+`.
Broadcasting functions allows to carry out elementwise operations on objects of different sizes.
The procedure involves increasing the size of the smaller object in such a way that both have the same size.


In [425]:
A 

2×2 Matrix{Int64}:
 1  2
 3  4

In [430]:
broadcast(+, A, 1)

2×2 Matrix{Int64}:
 2  3
 4  5

In [426]:
?broadcast

search: broadcast broadcast! Broadcast



```
broadcast(f, As...)
```

Broadcast the function `f` over the arrays, tuples, collections, [`Ref`](@ref)s and/or scalars `As`.

Broadcasting applies the function `f` over the elements of the container arguments and the scalars themselves in `As`. Singleton and missing dimensions are expanded to match the extents of the other arguments by virtually repeating the value. By default, only a limited number of types are considered scalars, including `Number`s, `String`s, `Symbol`s, `Type`s, `Function`s and some common singletons like [`missing`](@ref) and [`nothing`](@ref). All other arguments are iterated over or indexed into elementwise.

The resulting container type is established by the following rules:

  * If all the arguments are scalars or zero-dimensional arrays, it returns an unwrapped scalar.
  * If at least one argument is a tuple and all others are scalars or zero-dimensional arrays, it returns a tuple.
  * All other combinations of arguments default to returning an `Array`, but custom container types can define their own implementation and promotion-like rules to customize the result when they appear as arguments.

A special syntax exists for broadcasting: `f.(args...)` is equivalent to `broadcast(f, args...)`, and nested `f.(g.(args...))` calls are fused into a single broadcast loop.

# Examples

```jldoctest
julia> A = [1, 2, 3, 4, 5]
5-element Vector{Int64}:
 1
 2
 3
 4
 5

julia> B = [1 2; 3 4; 5 6; 7 8; 9 10]
5×2 Matrix{Int64}:
 1   2
 3   4
 5   6
 7   8
 9  10

julia> broadcast(+, A, B)
5×2 Matrix{Int64}:
  2   3
  5   6
  8   9
 11  12
 14  15

julia> parse.(Int, ["1", "2"])
2-element Vector{Int64}:
 1
 2

julia> abs.((1, -2))
(1, 2)

julia> broadcast(+, 1.0, (0, -2.0))
(1.0, -1.0)

julia> (+).([[0,2], [1,3]], Ref{Vector{Int}}([1,-1]))
2-element Vector{Vector{Int64}}:
 [1, 1]
 [2, 2]

julia> string.(("one","two","three","four"), ": ", 1:4)
4-element Vector{String}:
 "one: 1"
 "two: 2"
 "three: 3"
 "four: 4"

```


In [422]:
X = repeat(collect(1:100), 1000, 10000);
@show size(X)

size(X) = (100000, 10000)


(100000, 10000)

````{margin}
In addition to running the line of code, thanks to macro `@time` at the beginning of the line the execution time is returned.
````

In [423]:
@time X .+ 1;

  8.262623 seconds (4 allocations: 7.451 GiB, 0.93% gc time)


In [442]:
using Pipe

In [445]:
exp.( collect( range(log(1), stop=log(42), length=73) ) )

73-element Vector{Float64}:
  1.0
  1.0532831317160591
  1.1094053555575891
  1.1685179472442655
  1.2307802429398609
  1.2963600687379486
  1.3654341930319522
  1.4381888029888847
  1.5148200064111028
  1.5955343603388272
  1.6805494278182591
  1.7700943643360474
  1.8644105355008187
  ⋮
 23.727548568154436
 24.991826663810592
 26.323469455763327
 27.726066345998433
 29.203397991080454
 30.7594464927957
 32.3984061317844
 34.12469467309464
 35.94296527413145
 37.85811902709873
 39.87531816974189
 42.00000000000001

In [447]:
@pipe range(log(1), stop=log(42), length=73) |> collect |> exp.(_)

73-element Vector{Float64}:
  1.0
  1.0532831317160591
  1.1094053555575891
  1.1685179472442655
  1.2307802429398609
  1.2963600687379486
  1.3654341930319522
  1.4381888029888847
  1.5148200064111028
  1.5955343603388272
  1.6805494278182591
  1.7700943643360474
  1.8644105355008187
  ⋮
 23.727548568154436
 24.991826663810592
 26.323469455763327
 27.726066345998433
 29.203397991080454
 30.7594464927957
 32.3984061317844
 34.12469467309464
 35.94296527413145
 37.85811902709873
 39.87531816974189
 42.00000000000001

In [431]:
exp.([1 2 3])

1×3 Matrix{Float64}:
 2.71828  7.38906  20.0855

In [432]:
broadcast(exp, [1 2 3])

1×3 Matrix{Float64}:
 2.71828  7.38906  20.0855

In [424]:
@time X + repeat([1], 100000, 10000);

 29.899487 seconds (7 allocations: 14.901 GiB, 0.27% gc time)


We see that the broadcasted function is more than three times faster in the presented example.

In [385]:
repeat(A, 2, 1)

4×2 Matrix{Int64}:
 1  2
 3  4
 1  2
 3  4

In [383]:
?+

search: +



```
+(x, y...)
```

Addition operator. `x+y+z+...` calls this function with all arguments, i.e. `+(x, y, z, ...)`.

# Examples

```jldoctest
julia> 1 + 20 + 4
25

julia> +(1, 20, 4)
25
```

---

```
dt::Date + t::Time -> DateTime
```

The addition of a `Date` with a `Time` produces a `DateTime`. The hour, minute, second, and millisecond parts of the `Time` are used along with the year, month, and day of the `Date` to create the new `DateTime`. Non-zero microseconds or nanoseconds in the `Time` type will result in an `InexactError` being thrown.


In [369]:
@show broadcast(+, 1, [1 2;3 4])

@show broadcast(+, [0 1], [1 2;3 4])


# @show broadcast(+, [1 2 3], [1 2;3 4])

broadcast(+, 1, [1 2; 3 4]) = [2 3; 4 5]
broadcast(+, [0 1], [1 2; 3 4]) = [1 3; 3 5]


2×2 Matrix{Int64}:
 1  3
 3  5

In [381]:
.//( 1, [1 2;3 4])

2×2 Matrix{Rational{Int64}}:
 1//1  1//2
 1//3  1//4

In [382]:
[1 2]+1

LoadError: MethodError: no method matching +(::Matrix{Int64}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::Rational, ::Integer) at rational.jl:288
  ...

In [374]:
mean.([1 2 3])

1×3 Matrix{Float64}:
 1.0  2.0  3.0

* map and broadcasting
* dictionaries
* ranges
* functions
* for loops: many iterators, break, continue
* control flows: if ?:
* broadcasting exisitng functions
* anonymous functions
* plots
* DataFrames
* Pipes


In [227]:
using StatsBase

In [230]:
countmap([2; 2; 3; 4])

Dict{Int64, Int64} with 3 entries:
  4 => 1
  2 => 2
  3 => 1

In [231]:
?countmap

search: countmap



```
countmap(x; alg = :auto)
countmap(x::AbstractVector, w::AbstractVector{<:Real}; alg = :auto)
```

Return a dictionary mapping each unique value in `x` to its number of occurrences. A vector of weights `w` can be provided when `x` is a vector.

  * `:auto` (default): if `StatsBase.radixsort_safe(eltype(x)) == true` then use                    `:radixsort`, otherwise use `:dict`.
  * `:radixsort`:      if `radixsort_safe(eltype(x)) == true` then use the                    [radix sort](https://en.wikipedia.org/wiki/Radix_sort)                    algorithm to sort the input vector which will generally lead to                    shorter running time. However the radix sort algorithm creates a                    copy of the input vector and hence uses more RAM. Choose `:dict`                    if the amount of available RAM is a limitation.
  * `:dict`:           use `Dict`-based method which is generally slower but uses less                    RAM and is safe for any data type.


In [235]:
counts([1.5 1.5 3 100])

LoadError: MethodError: no method matching counts(::Matrix{Float64})
Closest candidates are:
  counts(::AbstractArray{T, N} where {T<:Integer, N}) at /Users/pytka/.julia/packages/StatsBase/XT7PT/src/counts.jl:85
  counts(::AbstractArray{T, N} where {T<:Integer, N}, ::UnitRange{T} where T<:Integer) at /Users/pytka/.julia/packages/StatsBase/XT7PT/src/counts.jl:79
  counts(::AbstractArray{T, N} where {T<:Integer, N}, ::UnitRange{T} where T<:Integer, ::AbstractWeights) at /Users/pytka/.julia/packages/StatsBase/XT7PT/src/counts.jl:81
  ...

In [236]:
using FreqTables

In [237]:
x = repeat(["a", "b", "c", "d"], outer=[100]);

In [245]:
x=[1; 1; 3; 4]
qwe = freqtable(x)

3-element Named Vector{Int64}
Dim1  │ 
──────┼──
1     │ 2
3     │ 1
4     │ 1

1

In [249]:
using ProgressLogging

In [250]:
@progress for i in 1:10
    sleep(0.1)
    
end

In [307]:
for i∈1:2
    for j∈ 15:.25:16 
        println("i=$i, j=$j")
    end
end

i=1, j=15.0
i=1, j=15.25
i=1, j=15.5
i=1, j=15.75
i=1, j=16.0
i=2, j=15.0
i=2, j=15.25
i=2, j=15.5
i=2, j=15.75
i=2, j=16.0


In [306]:
for i∈1:2, j∈ 15:.25:16
    println("i=$i, j=$j")
end

i=1, j=15.0
i=1, j=15.25
i=1, j=15.5
i=1, j=15.75
i=1, j=16.0
i=2, j=15.0
i=2, j=15.25
i=2, j=15.5
i=2, j=15.75
i=2, j=16.0


In [318]:
OLS(X,y) = inv(X'*X)*X'*y

OLS (generic function with 1 method)

In [319]:
qwe = collect(1:100)

100-element Vector{Int64}:
   1
   2
   3
   4
   5
   6
   7
   8
   9
  10
  11
  12
  13
   ⋮
  89
  90
  91
  92
  93
  94
  95
  96
  97
  98
  99
 100

In [324]:
map(x-> x%2==0 ? "Sargent" : "Lucas", qwe)

100-element Vector{String}:
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 ⋮
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"

In [325]:
broadcast(x-> x%2==0 ? "Sargent" : "Lucas", qwe)

100-element Vector{String}:
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 ⋮
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"
 "Lucas"
 "Sargent"

In [ ]:
a = [(x,y) for x ∈ 1:2, y ∈ 1:1:3]

2×3 Matrix{Tuple{Int64, Int64}}:
 (1, 1)  (1, 2)  (1, 3)
 (2, 1)  (2, 2)  (2, 3)

In [ ]:
((100-1)/(100-1))^1/.5 # * (10 - -2)

2.0

In [ ]:
-2 + ((100-1)/(100-1))^1/.5 * (10 - -2)

22.0

In [ ]:
balance_sheet = [(-2 + ((i-1)/(100-1))^(1/.5) * (10 - -2)) for i∈1:100]

100-element Vector{Float64}:
 -2.0
 -1.9987756351392716
 -1.995102540557086
 -1.9889807162534434
 -1.980410162228344
 -1.9693908784817875
 -1.955922865013774
 -1.9400061218243037
 -1.9216406489133762
 -1.9008264462809916
 -1.8775635139271503
 -1.8518518518518519
 -1.8236914600550964
  ⋮
  7.481481481481481
  7.698194061830426
  7.917355371900825
  8.138965411692686
  8.363024181205999
  8.589531680440771
  8.818487909397
  9.049892868074686
  9.28374655647383
  9.52004897459443
  9.758800122436487
 10.0

In [ ]:
income_shocks = exp.( range(log(1), stop=log(2), length= 25) )

25-element Vector{Float64}:
 1.0
 1.029302236643492
 1.0594630943592953
 1.0905077326652577
 1.122462048309373
 1.155352696872273
 1.189207115002721
 1.2240535433046553
 1.2599210498948732
 1.2968395546510096
 1.3348398541700344
 1.3739536474580891
 1.414213562373095
 1.4556531828421875
 1.4983070768766815
 1.5422108254079407
 1.5874010519681994
 1.6339154532410998
 1.681792830507429
 1.7310731220122861
 1.7817974362806785
 1.8340080864093424
 1.8877486253633868
 1.9430638823072117
 2.0

In [362]:
map(x -> begin
            x += 1
            2+2
            return(x)
        end,
        1:10)

10-element Vector{Int64}:
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11

In [ ]:
states = [(κ,ε) for κ ∈ balance_sheet, ε ∈ income_shocks]

100×25 Matrix{Tuple{Float64, Float64}}:
 (-2.0, 1.0)      (-2.0, 1.0293)      (-2.0, 1.05946)      …  (-2.0, 2.0)
 (-1.99878, 1.0)  (-1.99878, 1.0293)  (-1.99878, 1.05946)     (-1.99878, 2.0)
 (-1.9951, 1.0)   (-1.9951, 1.0293)   (-1.9951, 1.05946)      (-1.9951, 2.0)
 (-1.98898, 1.0)  (-1.98898, 1.0293)  (-1.98898, 1.05946)     (-1.98898, 2.0)
 (-1.98041, 1.0)  (-1.98041, 1.0293)  (-1.98041, 1.05946)     (-1.98041, 2.0)
 (-1.96939, 1.0)  (-1.96939, 1.0293)  (-1.96939, 1.05946)  …  (-1.96939, 2.0)
 (-1.95592, 1.0)  (-1.95592, 1.0293)  (-1.95592, 1.05946)     (-1.95592, 2.0)
 (-1.94001, 1.0)  (-1.94001, 1.0293)  (-1.94001, 1.05946)     (-1.94001, 2.0)
 (-1.92164, 1.0)  (-1.92164, 1.0293)  (-1.92164, 1.05946)     (-1.92164, 2.0)
 (-1.90083, 1.0)  (-1.90083, 1.0293)  (-1.90083, 1.05946)     (-1.90083, 2.0)
 (-1.87756, 1.0)  (-1.87756, 1.0293)  (-1.87756, 1.05946)  …  (-1.87756, 2.0)
 (-1.85185, 1.0)  (-1.85185, 1.0293)  (-1.85185, 1.05946)     (-1.85185, 2.0)
 (-1.82369, 1.0)  (-1.82369, 