## Data structures




(arrays)=
### Arrays

Arrays are one of the most important data structures for economists. They are equivalent of vectors and matrices in `Matlab` or `R`. 
Arrays are multi-dimensional objects containing numbers (or different objects).


A vector is a one-dimensional array. To get a row vector you use the following convention:

In [1]:
A = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

You get column vectors by using `;` as the separator of elements:

In [2]:
B = [1; 2; 3]

3-element Vector{Int64}:
 1
 2
 3

All elements of arrays must be of the same type. In case of type incompatibility across elements, coercion is performed:

In [3]:
@show c = [1 π 2.3]

@show typeof(c) #It's Float64 despite the first element being an integer.

c = [1 π 2.3] = [1.0 3.141592653589793 2.3]
typeof(c) = Matrix{Float64}


Matrix{Float64} (alias for Array{Float64, 2})

In [4]:
X = [1 2 3;
     3 4 5]

2×3 Matrix{Int64}:
 1  2  3
 3  4  5

It is a good practice to initialize arrays before assigning values to their elements.
To create an empty one-dimensional array with `K` elements of type `TYPE` 
you use `Array{TYPE}(undef, K)`.
Below an illustrating example:

In [5]:
Array{Float64}(undef, 10)

10-element Vector{Float64}:
 3.5e-323
 8.4e-323
 9.4e-323
 1.1e-322
 1.2e-322
 1.24e-322
 1.43e-322
 1.5e-322
 1.53e-322
 5.0e-324

Argument `undef` means that nothing particular is assigned to all elements.
Instead, existing values stored previously in the memory are assigned.

To create an array of dimensions $K\times N\times S\times W$ you use
`Array{TYPE}(undef, K, N, S, W)`.
Below an illustrating example:


In [6]:
Array{Int}(undef, 2, 3, 2, 2)

2×3×2×2 Array{Int64, 4}:
[:, :, 1, 1] =
 5630669552  5630669680  5630692496
 5630669616  5630691888  5630691984

[:, :, 2, 1] =
 5630669712  5630669808  5630692176
 5630669776  4930211680  4734170112

[:, :, 1, 2] =
 5630669904  5630670000  4734168896
 5630669968  5630692368  4927447440

[:, :, 2, 2] =
 4734170336  0  0
          0  0  0

To get an array with all elements constant, you use command `fill`:

In [7]:
A = fill(π^2, 4, 3)

4×3 Matrix{Float64}:
 9.8696  9.8696  9.8696
 9.8696  9.8696  9.8696
 9.8696  9.8696  9.8696
 9.8696  9.8696  9.8696

To get an object of the same size and data type, function `similar` can be useful. Elements of the new objects will contain information previously allocated in the memory.

In [8]:
B = similar(A)

4×3 Matrix{Float64}:
 2.31091e-314  2.31091e-314  2.31091e-314
 2.31091e-314  2.31091e-314  2.31091e-314
 2.31091e-314  2.31091e-314  2.31091e-314
 2.31091e-314  2.31091e-314  2.30435e-314

Arrays with zero elements can be constructed with `zeros`:

In [9]:
zeros(3,2)

3×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

To get an identity square matrix of dimension $K$ function `I` from package `LinearAlgebra` can be used:

````{margin}
To load package to the memory, you use `using PackageName`. To install packages you use `Pkg` package:
    ```
    using Pkg; Pkg.add("PackageName")
    ```
````

In [10]:
using LinearAlgebra
I(5)

5×5 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  1  ⋅  ⋅
 ⋅  ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  ⋅  1

```{margin}
`I` generates a matrix with boolean elements (with `true` and `false` values) but it can be used normally with arrays of other numeric types thanks to coercion.
```

#### Simple array operations

Except square-bracket notations, accessing arrays in `Julia` is almost one-to-one analogy to `Matlab`:

In [11]:
A = [1 2 3 4 5;
     6 7 5 9 12]

2×5 Matrix{Int64}:
 1  2  3  4   5
 6  7  5  9  12

In [12]:
size(A)

(2, 5)

In [13]:
A[1,:] #1st row

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [14]:
A[:,1] #1st column

2-element Vector{Int64}:
 1
 6

In [15]:
A[:,[1,3]] #1st and 3rd column

2×2 Matrix{Int64}:
 1  3
 6  5

In [16]:
A[:,3:end] #from 3rd to the last columns

2×3 Matrix{Int64}:
 3  4   5
 5  9  12

In [17]:
A[1,3:end] #1st row and from 3rd to the last columns

3-element Vector{Int64}:
 3
 4
 5

Just like with scalars, arithmetic operations on arrays of _the same dimensions_ work in an analogous way:

In [18]:
A = [1 2;3 4];
B = I(2);

In [19]:
A + B

2×2 Matrix{Int64}:
 2  2
 3  5

In [20]:
A*A

2×2 Matrix{Int64}:
  7  10
 15  22

In [21]:
A

2×2 Matrix{Int64}:
 1  2
 3  4

In [22]:
A' #transposition

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

In [23]:
A^(-1) #invert matrix

2×2 Matrix{Float64}:
 -2.0   1.0
  1.5  -0.5

In [24]:
maximum(A) #notice that `max`` works in a bit different way than in Matlab!

4

In [25]:
A^(-1)*A 

2×2 Matrix{Float64}:
 1.0          0.0
 2.22045e-16  1.0

In [26]:
kron(A,I(3))

6×6 Matrix{Int64}:
 1  0  0  2  0  0
 0  1  0  0  2  0
 0  0  1  0  0  2
 3  0  0  4  0  0
 0  3  0  0  4  0
 0  0  3  0  0  4

Nonetheless, if we try to add an object of incompatible dimensions (including scalars),
we will get an error message, just like in an example below:

In [27]:
A + 1

LoadError: MethodError: no method matching +(::Matrix{Int64}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::Rational, ::Integer) at rational.jl:288
  ...

This can be perceived as a particularly bizzare and excessively formal thing. 
That said, at the development stage there were reasons for this.
Furthermore, notice that in Mathematics this type of operations, $\mathbb{A}+1$, in most cases is also forbidden.
One (extremely inefficient but didactically useful) solution to this problem is to increase the size of the smaller object by using `repeat`.
This function constructs an array by repeating the input _array_ a given number of times in each out of the provided dimension.

Thus, to compute $\mathbb{A}+1,$ we have to increase the size of $1$ in such a way that the new object fits the size of $\mathbb{A}$.
As we remember the size of $\mathbb{A}$ is $2\times 2.$
Just to double check, let's use function `size`.

In [ ]:
size(A)

(2, 2)

```{margin}
The first argument of `repeat` is the input array (note that we need to write the array form `[1]` fort this reason that a scalar object `1` is not accepted by the function), next arguments tell us how many times in each dimension the object should be repeated.
```

Below you can find `repeat` at play:

In [ ]:
repeat([1], 3)

3-element Vector{Int64}:
 1
 1
 1

In [ ]:
repeat([1], 3, 2)

3×2 Matrix{Int64}:
 1  1
 1  1
 1  1

In [ ]:
repeat([1], 4, 3, 2)

4×3×2 Array{Int64, 3}:
[:, :, 1] =
 1  1  1
 1  1  1
 1  1  1
 1  1  1

[:, :, 2] =
 1  1  1
 1  1  1
 1  1  1
 1  1  1

In [ ]:
repeat([1; 2], 2, 3) #input argument: column vector

4×3 Matrix{Int64}:
 1  1  1
 2  2  2
 1  1  1
 2  2  2

In [ ]:
repeat([1 2], 2, 3) #input argument: row vector

2×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2

Consequently, we are in the position to compute $\mathbb{A}+1:$

In [ ]:
A + repeat([1], 2, 2)

2×2 Matrix{Int64}:
 2  3
 4  5

An addition of two arrays of different sizes can be conducted analogously:

In [ ]:
A + repeat([0; 1], 1, 2)

2×2 Matrix{Int64}:
 1  2
 4  5

:::{note}
That being said, by no means use this approach in your daily use.
A _much more recommended_ and **efficient** way to operate on objects of different sizes is to use broadcasting or mapping.
I discuss it in more details in [one of the further secions](broadcasting).
:::

(assign)=
#### Assignment operator (`=`) and arrays: easy for Pythonistas, confusing for Matlabians

What can be quite confusing at first for people with the `Matlab` background is how the assignment operator (`=`) works with arrays in `Julia`. 
In `Matlab` if we want to create a matrix `V1` that is a copy of another matrix `V0` it is enough to write:

```
    V1=V0
```

```{note}
Henceforth, there are two _separate_ matrices in the memory, `V1` and `V0`. 
Any changes in either of those will not affect the other one.
In `Julia` this works in a very different way. 
Exactly like in `Python`, running `V1=V0` will create a new _pointer_ to the memory allocated for `V0`. 
Both objects, `V1` and `V0`, share the same information.
Consequently, any changes in the memory through accessing `V1` will affect the data pointed by `V0`, and vice versa.
Below you can find an illustration of this language feature.
```

In [ ]:
@show V₀ = [1 2 3];

V₀ = [1 2 3] = [1 2 3]


In [ ]:
@show V₁ = V₀;


V₁ = V₀ = [1 2 3]


Running `V₁ = V₀` will create a new pointer to the memory associated with `V₀`.
Now changes in either of those objects will affect both pointers:

In [ ]:
@show V₁[1] = 420;
@show V₁;
@show V₀;

@show V₀[3] = 128;
@show V₁;
@show V₀;

V₁[1] = 420 = 420
V₁ = [420 2 128]
V₀ = [420 2 128]
V₀[3] = 128 = 128
V₁ = [420 2 128]
V₀ = [420 2 128]


```{margin}
_Note to myself:_ explain it using better words.
```

This feature of `Julia` can be especially confusing in iterative procedures with updating values, such as value function iterations. 
In this case, trying to create a copy of one array but making rather a new pointer instead will result in meeting the convergence criterion immediately after the first iteration (_terrible sentence_).
Obviously, this will not be correct.



A remedy to this issue can be simply addressed by using `deepcopy`, which creates a _new object in the memory_ that contains the same information as the copied object.

In [ ]:
@show V₀ = [1 2 3];
@show V₁ = deepcopy(V₀);

V₀ = [1 2 3] = [1 2 3]
V₁ = deepcopy(V₀) = [1 2 3]


Now changes in either of those objects _will not_ affect values pointed by the other object:

In [ ]:
@show V₁[1] = 420;
@show V₁;
@show V₀;

@show V₀[3] = 128;
@show V₁;
@show V₀;

V₁[1] = 420 = 420
V₁ = [420 2 3]
V₀ = [1 2 3]
V₀[3] = 128 = 128
V₁ = [420 2 3]
V₀ = [1 2 128]


An important thing that should be also stressed is that this feature works only in the presence of assignments without additional operations.
If, for instance, code `V₁ = 2*V₀` involves two operations: (1) multiplication `*(2,V₀)`; and (2) making pointer `V₁` to memory containing _results_ from computing `*(2,V₀)` in the past.
This means that memory spaces pointed by `V₁` and by `V₀` are two different things.

In [ ]:
@show V₀ = [1 2 3];
@show V₁ = 2*V₀;

V₀ = [1 2 3] = [1 2 3]
V₁ = 2V₀ = [2 4 6]


In [ ]:
@show V₁[1] = 420;
@show V₁;
@show V₀;

@show V₀[3] = 128;
@show V₁;
@show V₀;

V₁[1] = 420 = 420
V₁ = [420 4 6]
V₀ = [1 2 3]
V₀[3] = 128 = 128
V₁ = [420 4 6]
V₀ = [1 2 128]


### Dictionaries


Dictionaries are very useful objects that are particularly useful in my daily workflow. 
They contain different objects and data structures of those types can be very different.
Dictionaries are initialized with `Dict` and the list of the elements take arguments in the form `"name_of_the_object" => object`.
An illustration below:



In [30]:
my_first_dict = Dict("X" => 2,
                     "Y" => 1:10)

Dict{String, Any} with 2 entries:
  "Y" => 1:10
  "X" => 2

Alternatively you can use a bit different notation, which I personally prefer (and I am not sure why):  `Dict([ ("name_of_the_object1", object1) ])`.
For example, if we want to create an object containing all parameters of our model, dictionaries are good candidates for it:

In [36]:

params = Dict([ 
                ("β" , (1/1.04)^(1/12)),
                ("b" , [.55 0]) ,
                ("vec_states" , 1:2) ,
                ("π", [1:10 20:29])
            ])


Dict{String, Any} with 4 entries:
  "b"          => [0.55 0.0]
  "π"          => [1 20; 2 21; … ; 9 28; 10 29]
  "vec_states" => 1:2
  "β"          => 0.996737

Accessing elements of dictionaries has some similarities with arrays. The main difference is that we have to use names in quotates instead of indices:

In [37]:
@show params["β"]
params["π"]

params["β"] = 0.9967369426185624


10×2 Matrix{Int64}:
  1  20
  2  21
  3  22
  4  23
  5  24
  6  25
  7  26
  8  27
  9  28
 10  29

We can normally work on objects inside dictionaries. 
Suppose we want to increase values of all rows but the last one of the first column of array `π` by one we can do it by: 

In [38]:
params["π"][1:(end-1),1]  .+= 1;
params["π"]

10×2 Matrix{Int64}:
  2  20
  3  21
  4  22
  5  23
  6  24
  7  25
  8  26
  9  27
 10  28
 10  29

We can also add new elements to existing dictionaries. It is super simple:

In [54]:
params["Σ"] = 12

12

Now in in `params` there is a new object `Σ`:

In [59]:
params 

Dict{String, Any} with 5 entries:
  "Σ"          => 12
  "b"          => [0.55 0.0]
  "π"          => [2 20; 3 21; … ; 10 28; 10 29]
  "vec_states" => 1:2
  "β"          => 0.996737

In my own workflow, dictionaries are super useful for putting all blocks of models into one object.
I create a dictionary `economy` with all parameters, value functions, simulations inside.
Thanks to this during analyses I can explore different parametrizations, counterfactual calibrations and what not in a very organized way.



```{note}
You have to remember the assignment operator `=` with whole dictionaries works in a very similar way as with arrays, _i.e._ it refers to memory containing information rather than information itself.
```

In [ ]:
equation_copy = equation;

println("Before assignment:")
@show equation["c"];
@show equation_copy["c"];


println("ASSIGNMENT: equation_copy[\"c\"] = 420")
equation_copy["c"] = 420;

println("After assignment:")
@show equation["c"];
@show equation_copy["c"];


Before assignment:
equation["c"] = π
equation_copy["c"] = π
ASSIGNMENT: equation_copy["c"] = 420
After assignment:
equation["c"] = 420
equation_copy["c"] = 420


(unpack)=
#### Too many repetitions of dictionary names? `@unpack` should help!

(multiply_coefs)=
```{note}
Suppose that we have a dictionary `equation` containing a range of argumnents $\mathbf{x}=\left(1+\frac{(i-1)}{10}\right)_{i=1}^{100}$ and values of coefficients $(a=1,b=12,c=\pi)$ characterizing a certain quadratic equation $ax^2 + bx +c.$ 
```

Then, our dictionary will be of the following form:


In [48]:
equation  = Dict([
                    ("x" , collect(range(1, step=.1, length=100)) ),
                    ("a", 1),
                    ("b", 12),
                    ("c", π)
                ])

Dict{String, Any} with 4 entries:
  "c" => π
  "x" => [1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9  …  10.0, 10.1, 10.2…
  "b" => 12
  "a" => 1

(polyn_eval)=
```{note}
Now suppose we want to evaluate the function calibrated with $(a=1,b=12,c=\pi)$ at $\mathbb{x}.$
```
One way to do it is as follows:


```{margin}
Here I broadcast functions using `@.` macro.
Broadcasting in general is discussed in [this](broadcasting) section, while `@.` macro in [this](at_dot) subsection.
```

In [3]:
equation["y"] = @. equation["a"]*equation["x"]^2 + equation["b"]*equation["x"] + equation["c"]

100-element Vector{Float64}:
  16.141592653589793
  17.551592653589793
  18.981592653589793
  20.431592653589796
  21.90159265358979
  23.391592653589793
  24.9015926535898
  26.431592653589792
  27.981592653589797
  29.55159265358979
  31.141592653589793
  32.751592653589796
  34.38159265358979
   ⋮
 216.78159265358983
 219.95159265358978
 223.14159265358978
 226.35159265358976
 229.58159265358978
 232.8315926535898
 236.10159265358982
 239.39159265358978
 242.70159265358978
 246.03159265358974
 249.38159265358982
 252.7515926535898

The code works but it does not have the nicest look and might be difficult to change.
In this case, macro `@unpack` from package `Parameters` can be helpful in making the code more legible.
This macro has the following syntax:  `@unpack object_1, object_2 = dictionary_1`.
`@unpack` extracts objects with names `object_1` and `object_2` from `dictionary_1` and makes them available in the current local scope. `dictionary_1` might have other objects inside but `@unpack` extracts only those explicitly mentioned objects.
Below you can see how it works

```{margin}
Note to myself: in the future you need to write a section on scopes.
```

In [4]:
@show a #object a is only defined in dictionary equation, so you cannot access it

LoadError: UndefVarError: a not defined

In [5]:
using Parameters
@unpack a, b, c, x = equation
@show a #now it works


a = 1


1

Now to evaluate our quadratic function at $\mathbb{x}$ we can do it by:

In [6]:
equation["y"] = @. a*x^2 + b*x + c

100-element Vector{Float64}:
  16.141592653589793
  17.551592653589793
  18.981592653589793
  20.431592653589796
  21.90159265358979
  23.391592653589793
  24.9015926535898
  26.431592653589792
  27.981592653589797
  29.55159265358979
  31.141592653589793
  32.751592653589796
  34.38159265358979
   ⋮
 216.78159265358983
 219.95159265358978
 223.14159265358978
 226.35159265358976
 229.58159265358978
 232.8315926535898
 236.10159265358982
 239.39159265358978
 242.70159265358978
 246.03159265358974
 249.38159265358982
 252.7515926535898

You have to remember that in `@unpack`, the assignment (`=`) operator works normally... for `Julia`. This means that if `object_1` is a scalar while `object_2` is an array, working with those objects can be very different.
This topic was discussed in [this](assign) section.
Below you can find an example illustrating those differences:


In [7]:
@show equation["a"];
@show a;

@show a += 1;

@show equation["a"]; # `a += 1;` didn't change  the value of `equation["a"]`
@show a;             # `a += 1;`        changed the value of `a`

equation["a"] = 1
a = 1
a += 1 = 2
equation["a"] = 1
a = 2


2

In [8]:
@show equation["x"];
@show x;


@show x .+= 1;

@show equation["x"]; # `x .+= 1;`        CHANGED the value of `equation["x"]`
@show x;             # `x .+= 1;`        changed the value of `x`

equation["x"] = [1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9.0, 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9, 10.0, 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9]
x = [1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9.0, 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9, 10.0, 10.1, 10.2, 

100-element Vector{Float64}:
  2.0
  2.1
  2.2
  2.3
  2.4
  2.5
  2.6
  2.7
  2.8
  2.9
  3.0
  3.1
  3.2
  ⋮
 10.8
 10.9
 11.0
 11.1
 11.2
 11.3
 11.4
 11.5
 11.6
 11.7
 11.8
 11.9

While `a+=1` _did not_ have impact on `equation["a"]`, `x .+= 1` affected `equation["x"]`. It is important to remember this feature of the language.

### Ranges



Ranges are quite intuitive objects.
They collect elements from a certain range of values.
They can be created either by using `:` operator (just like in `R` and `Matlab`) or by using `range` function.
For instance, if we want to create a range from 5 through 120, we can use two options:

In [ ]:
@show 5:120;
@show range(5, stop=120);

5:120 = 5:120
range(5, stop = 120) = 5:120


Notice that you are not allowed to use `range(5,120)` because at least one of `length`, `stop`, or `step` must be specified explicitely.


If we want, we can set the size step. Again, it can be done in two ways:

In [ ]:
@show 5:.5:120;
@show range(5, stop=120, step=.5);

5:0.5:120 = 5.0:0.5:120.0
range(5, stop = 120, step = 0.5) = 5.0:0.5:120.0


You can perform normal arithmetic operations:

In [ ]:
(1:5)*2

2:2:10

However, be careful about the order of operations. 
Arithmetic operations have a higher priority in `Julia`.
For `Matlab` users that is the same, but it might be problematic for `R` users, where the order is different.
In `Julia`if you type `1:5+1`, you will give you `1:6`, while in `R` you will get `2:6`.

In [ ]:
1:5+1

1:6

Another important difference between other languages and `Julia` is the fact that arrays and ranges are not compatible with each other.
This means that arithmetic operations will give you an error message, even if objects are of the same size: 

In [ ]:
1:3 + [1; 2; 3]

LoadError: MethodError: no method matching +(::Int64, ::Vector{Int64})
For element-wise addition, use broadcasting with dot syntax: scalar .+ array
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::Union{Int16, Int32, Int64, Int8}, ::BigInt) at gmp.jl:534
  ...

You can extract all element from a range and create an array by using `collect`:

In [ ]:
collect(1:3)

3-element Vector{Int64}:
 1
 2
 3

In this case, arithmetic operations are allowed:


In [ ]:
collect(1:3) + [1; 2; 3]

3-element Vector{Int64}:
 2
 4
 6

### Tuples

To be written. An example of a tuple:

In [ ]:
(1,2,3)

(1, 2, 3)

### Sets

To be written